### ISSUE TITLE
Jupyter latest release

### ISSUE THREAD

**Issue by SkBlaz** [vpodpecan/representation_learning#14]
If installing according to: 
`https://jupyter.org/install` the jupyter notebooks (most recent version), deny access to opening a html to a user (https://github.com/jupyter/notebook/issues/4500).

However, the following did the trick:
```
pip install notebook==5.6.0
```

Note that these links still work fine.
![image](https://user-images.githubusercontent.com/10035780/101245653-8c6dad80-370e-11eb-8380-a9727d25a796.png)

**Comment by vpodpecan** [comment]
Are you using `notebook` or `jupyterlab`? In any case, copy and paste always works fine.

**Comment by SkBlaz** [comment]
jupyterlab
