### ISSUE TITLE
mp2v tsne plot

### ISSUE THREAD

**Issue by SkBlaz** [vpodpecan/representation_learning#15]
Regarding the following image:
![image](https://user-images.githubusercontent.com/10035780/101245696-da82b100-370e-11eb-8944-9289b4078452.png)

The spiral-like shape can emerge due to fitting to some high-dimensional artefacts. Perhaps using more neighbors would be more suitable here.

Additionally, I'd add some text in the lines of:

`Note that t-SNE-based visualizations are a means for qualitative exploration and can depend highly on the considered hyperparameter settings. To further evaluate the clusters' properties, additional analysis would need to be conducted`

**Comment by vpodpecan** [comment]
Updated.
