### ISSUE TITLE
StarSpace notebook v2

### ISSUE THREAD

**Issue by SkBlaz** [vpodpecan/representation_learning#19]
What is the point of this exactly:
![image](https://user-images.githubusercontent.com/10035780/101246429-9219c200-3713-11eb-83ba-c56c0f5a8c42.png)

is it like a baseline? If so, I suggest that the comparison is fair, repeated a couple of times with the starspace properly tuned.

**Comment by vpodpecan** [comment]
It is a baselike very similar to the one used in the paper. Regarding the tuning of StarSpace issue #18 is still open.
