### ISSUE TITLE
pyrdm + py3.9

### ISSUE THREAD

**Issue by SkBlaz** [vpodpecan/representation_learning#2]
Making environments with python=3.9  (default in conda) prohibits subsequent installation of pyrdm.

**Comment by vpodpecan** [comment]
Python 3.9 is very new, many packages do not support it yet. The best support currently is for the latest 3.6 branch. I would also avoid conda if possible. I think we need to include instructions how to setup the jupyter environment in Chapter 1. That is
- install python 3 (preferably 3.6 or 3.7)
- make a local virtual environment (preferably separate for each notebook to avoid potential clashes)
- using pip install the packages for the notebook and also jupyterlab
- start jupyterlab

**Comment by SkBlaz** [comment]
I'm not sure this is solved then. Just tried and the new conda assumes py3.9, which is rather annoying. There are at least two more meta options:
1. virtualenv as you said
2. conda yml file I've been currently using (should be simple to replicate)
3. dockerized environment, which just runs notebooks directly

**Comment by vpodpecan** [comment]
Creating a virtualenv is very easy and has zero dependencies. This is the way to go for this book so I close this issue.
