### ISSUE TITLE
pythonRDM - example final

### ISSUE THREAD

**Issue by SkBlaz** [vpodpecan/representation_learning#21]
The final tree is fine:
![image](https://user-images.githubusercontent.com/10035780/101246479-ed4bb480-3713-11eb-9956-4429cd21c8f6.png)

however, I'm not sure exactly what the final message is here? Perhaps this combined with performance, showing that it performs better than random would be more informative?

**Comment by vpodpecan** [comment]
python-rdm got a massive update. There are now two examples: TreeLiker on trains and RSD on mutagenesis. There is no special message for the tree you mentioned, it's just a demo how to get a decision tree out of more than one table. The resulting tree is small and easy to understand if the induced attributes are printed out. The RSD example is a bit more realistic so there we do not report the tree but the actual classification results.

**Comment by vpodpecan** [comment]
Update: with a bigger picture of the tree the text output is no longer required so I deleted it.
