### ISSUE TITLE
The BERT notebook

### ISSUE THREAD

**Issue by SkBlaz** [vpodpecan/representation_learning#22]
Perhaps it could be clarified that "val_dataloader" automatically loads only the validation part of the data which in this case is the _test_ data:

![image](https://user-images.githubusercontent.com/10035780/101246725-67c90400-3715-11eb-8a1c-645b4d0dff51.png)

**Comment by vpodpecan** [comment]
Yes, there was inconsistency in terminology. The finetuning script used validation and the notebook used testing. I replaced "test" with "val" in the notebook and re-run everything so this issue can be closed.
