### ISSUE TITLE
word2vec notebook

### ISSUE THREAD

**Issue by SkBlaz** [vpodpecan/representation_learning#24]
![image](https://user-images.githubusercontent.com/10035780/101246831-f0e03b00-3715-11eb-9e60-493a3280ca98.png)

This matrix is symmetric. I'd suggest rather somehting in the lines of

```
def get_lower_tri_heatmap(df, output="cooc_matrix.png"):
    mask = np.zeros_like(df, dtype=np.bool)
    mask[np.triu_indices_from(mask)] = True

    # Want diagonal elements as well
    mask[np.diag_indices_from(mask)] = False

    # Set up the matplotlib figure
    f, ax = plt.subplots(figsize=(11, 9))

    # Generate a custom diverging colormap
    cmap = sns.diverging_palette(220, 10, as_cmap=True)

    # Draw the heatmap with the mask and correct aspect ratio
    sns_plot = sns.heatmap(data, mask=mask, cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})
    # save to file
    fig = sns_plot.get_figure()
    fig.savefig(output)
```

**Comment by vpodpecan** [comment]
What would be the benefit of this? matshow() is used here just to get better overview of the printed table to quickly identify extremes. IMHO, it is also beneficial that the symmetry is shown because it reflects this property of pairwise cosine siminarity.

**Comment by SkBlaz** [comment]
The benefit would be a non redundant matrix. Rhe cosine metric is a proper metric, not sure visualization is needed to see this

**Comment by vpodpecan** [comment]
It makes easy to see which documents are similar and which are not. For example, the white square at (4,6) really stands out at the first glance. Outlier documents can be easily spotted by looking for mostly white rows/columns. Clusters are also often visible, for example, first six documents. I will add more explanation into the notebook and close this issue for now.
