### ISSUE TITLE
Some general remarks

### ISSUE THREAD

**Issue by SkBlaz** [vpodpecan/representation_learning#25]
1. It would be much more user-friendly to have a single requirements file that apply to all notebooks
2. Are all used libraries properly cited (license-wise)

**Comment by vpodpecan** [comment]
1. I develop using a single virtual environment so this works perfectly ok. However, just to be on the safe side wrt. future updates we recommned in the book to use a separate environment for every notebook. In any case, the first cell in every notebook installs all the required packages so the user only needs to create a venv and install jupyterlab and the notebook will take care of the rest.
2. Data sources, papers, and algorithms are cited in the notebooks. Libraries mentioned in the book are also cited there.
