### ISSUE TITLE
Larger dataset

### ISSUE THREAD

**Issue by SkBlaz** [vpodpecan/representation_learning#6]
Hej, pri propDRM primeru bi bilo super, če lahko namesto trains v enak format pretopiš npr. https://relational.fit.cvut.cz/dataset/Carcinogenesis, ali pa https://relational.fit.cvut.cz/dataset/Mutagenesis,

bi bilo top!

**Comment by vpodpecan** [comment]
Ok, bom takoj ko utegnem, pa ti sporočim.

**Comment by SkBlaz** [comment]
Super, hvala!

**Comment by vpodpecan** [comment]
I added the [largest of the mutagenesis databases](https://relational.fit.cvut.cz/dataset/Mutagenesis) in CSV format into python-rdm under examples: [https://github.com/xflows/rdm/tree/master/examples/data/mutagenesis](https://github.com/xflows/rdm/tree/master/examples/data/mutagenesis).
For the [Carcinogenesis](https://relational.fit.cvut.cz/dataset/Carcinogenesis) there are 82 foreign key constraint violations for table `atom` and many more for `sbond_` tables so I think it doesn't make sense to dive into that at the moment.
