### ISSUE TITLE
YAP prolog repo yap-6.3 is no more

### ISSUE THREAD

**Issue by vpodpecan** [vpodpecan/representation_learning#8]
Looks like that the author **deleted** the YAP 6.3 repository [https://github.com/vscosta/yap-6.3](https://github.com/vscosta/yap-6.3) from GitHub! Now what? The link in python-rdm notebook is dead and there is no way to get the 6.3.3 version which was known to work. The current repository is [https://github.com/vscosta/yap](https://github.com/vscosta/yap) but is has no branches, no tags, and no releases.

**Comment by SkBlaz** [comment]
One option would be to keep the freezed version of 6.3.3. as part of pyRDM
perhaps. Otherwise a docker option remains

**Comment by vpodpecan** [comment]
I added a zip of the 6.3.3 branch into the [xflows/rdp repo](https://github.com/xflows/rdm/blob/master/yap-6.3.3/yap-6.3.3.zip).
